micronaut:
  application:
    name: fretes

grpc:
  server:
    health:
      enabled: true

endpoints:
#  all:  # boa pr√°tica
#    port: 8085
#    sensitive: true
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS